### ISSUE TITLE
正隊員・準隊員 制度スタート キックオフミーティング(9/5 19:00〜) Agenda

### ISSUE THREAD

**Issue by mapconcierge** [dronebird/docs4dronebirds#17]
# 趣旨
正隊員・準隊員 制度がはじまり、ドローンバードの活動方針や今後の具体的な活動内容をディスカッションします。

# スケジュール
* 2020年9月5日(土) 19:00〜21:00 on Zoom

# 第一部(19:00-19:30)
* Zoom動画記録→編集して公開？
* コンセプト、経緯、ふりかえり
* 隊員募集方法
* 災害協定拡張重点エリア共有（各自で交渉をひろげる）。
* タスクにコミットしよう！

# 第二部(20:10-21:00)
## LT(5分プレゼン)
* 藤井副隊長
* 発表者募集中(誰も手を挙げなければ古橋から指名します)

## 自己紹介タイム
* 活動地域、所有機体、スキルなどそれぞれ1分

**Comment by nashitakahashi** [comment]
隊員自己紹介(活動地域、所有機体、スキルなど

**Comment by fzeeplus** [comment]
第１部と第２部に分けないですかね？

**Comment by fzeeplus** [comment]
> 隊員自己紹介(活動地域、所有機体、スキルなど

後半の内容になりますかね。

**Comment by fzeeplus** [comment]
GitGubに慣れていない方向けにフォローが必要かも。

**Comment by fairlaterfair** [comment]
定期訓練内容のや望や希望をーのをヒアリングするとよいと思います。
